import { MovieRecommendation } from './types';

export const mockRecommendations: MovieRecommendation[] = [
  {
    id: '1',
    title: 'Kantara',
    type: 'movie',
    platforms: ['Prime Video', 'Hotstar'],
    imdbRating: 8.2,
    moodScore: 96,
    summary: 'A mystical Kannada thriller that blends folklore with stunning visuals, perfect for an inspiring and mind-blowing experience.',
    trailerUrl: 'https://www.youtube.com/watch?v=8mrVmf239GU',
    language: 'Kannada',
    subtitles: ['English', 'Hindi', 'Tamil', 'Telugu'],
    dubbing: ['Hindi', 'Tamil', 'Telugu'],
    poster: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400',
    year: 2022,
    genre: ['Action', 'Drama', 'Thriller'],
    duration: '148 min',
    whyRecommended: 'You want to feel inspired and mind-blown — this Kannada masterpiece combines stunning cinematography with deep cultural storytelling that will leave you amazed.'
  },
  {
    id: '2',
    title: 'RRR',
    type: 'movie',
    platforms: ['Netflix', 'Prime Video'],
    imdbRating: 7.9,
    moodScore: 94,
    summary: 'An epic Telugu action drama about friendship and revolution, featuring spectacular action sequences and emotional depth.',
    trailerUrl: 'https://www.youtube.com/watch?v=f_vbAtFSEc0',
    language: 'Telugu',
    subtitles: ['English', 'Hindi', 'Tamil', 'Kannada'],
    dubbing: ['Hindi', 'Tamil', 'Malayalam'],
    poster: 'https://images.pexels.com/photos/1117132/pexels-photo-1117132.jpeg?auto=compress&cs=tinysrgb&w=400',
    year: 2022,
    genre: ['Action', 'Drama', 'History'],
    duration: '187 min',
    whyRecommended: 'You\'re feeling happy and want entertainment — this Telugu blockbuster delivers incredible action, emotion, and visual spectacle perfect for an uplifting experience.'
  },
  {
    id: '3',
    title: 'The Good Place',
    type: 'series',
    platforms: ['Netflix', 'Prime Video'],
    imdbRating: 8.2,
    moodScore: 92,
    summary: 'A comedy about the afterlife that\'s both hilarious and deeply philosophical, perfect for lifting spirits.',
    trailerUrl: 'https://www.youtube.com/watch?v=RfBgT5djaQw',
    language: 'English',
    subtitles: ['Hindi', 'Tamil', 'Telugu', 'Spanish', 'French'],
    dubbing: ['Hindi', 'Spanish'],
    poster: 'https://images.pexels.com/photos/3945313/pexels-photo-3945313.jpeg?auto=compress&cs=tinysrgb&w=400',
    year: 2016,
    genre: ['Comedy', 'Fantasy', 'Drama'],
    duration: '22 min episodes',
    whyRecommended: 'You\'re feeling stressed and want to be uplifted — this series combines humor with heartwarming moments that will leave you feeling optimistic about life.'
  },
  {
    id: '4',
    title: 'Squid Game',
    type: 'series',
    platforms: ['Netflix'],
    imdbRating: 8.0,
    moodScore: 89,
    summary: 'A gripping Korean survival thriller that keeps you on the edge of your seat with social commentary.',
    trailerUrl: 'https://www.youtube.com/watch?v=oqxAJKy0ii4',
    language: 'Korean',
    subtitles: ['English', 'Hindi', 'Tamil', 'Telugu', 'Spanish', 'French'],
    dubbing: ['English', 'Hindi', 'Spanish'],
    poster: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400',
    year: 2021,
    genre: ['Thriller', 'Drama', 'Action'],
    duration: '60 min episodes',
    whyRecommended: 'You\'re feeling bored and want to be mind-blown — this Korean series offers intense storytelling that will completely captivate your attention.'
  },
  {
    id: '5',
    title: 'Zindagi Na Milegi Dobara',
    type: 'movie',
    platforms: ['Netflix', 'Prime Video'],
    imdbRating: 8.2,
    moodScore: 91,
    summary: 'Three friends on a Spanish adventure discover themselves and the meaning of friendship.',
    trailerUrl: 'https://www.youtube.com/watch?v=tlMPtbK6uDM',
    language: 'Hindi',
    subtitles: ['English', 'Tamil', 'Telugu', 'Kannada'],
    dubbing: ['English', 'Tamil'],
    poster: 'https://images.pexels.com/photos/1117132/pexels-photo-1117132.jpeg?auto=compress&cs=tinysrgb&w=400',
    year: 2011,
    genre: ['Adventure', 'Comedy', 'Drama'],
    duration: '155 min',
    whyRecommended: 'You want to feel inspired and entertained — this Hindi film beautifully captures the spirit of adventure and friendship, perfect for a mood boost.'
  },
  {
    id: '6',
    title: 'Minnal Murali',
    type: 'movie',
    platforms: ['Netflix'],
    imdbRating: 7.8,
    moodScore: 88,
    summary: 'A Malayalam superhero film that combines humor, heart, and spectacular action in a small-town setting.',
    trailerUrl: 'https://www.youtube.com/watch?v=Ey73oTO7SuY',
    language: 'Malayalam',
    subtitles: ['English', 'Hindi', 'Tamil', 'Telugu', 'Kannada'],
    dubbing: ['Hindi', 'Tamil', 'Telugu'],
    poster: 'https://images.pexels.com/photos/3945313/pexels-photo-3945313.jpeg?auto=compress&cs=tinysrgb&w=400',
    year: 2021,
    genre: ['Action', 'Comedy', 'Superhero'],
    duration: '158 min',
    whyRecommended: 'You want to feel entertained and uplifted — this Malayalam superhero film offers the perfect blend of humor, heart, and spectacular action.'
  },
  {
    id: '7',
    title: 'Money Heist (La Casa de Papel)',
    type: 'series',
    platforms: ['Netflix'],
    imdbRating: 8.2,
    moodScore: 90,
    summary: 'A Spanish heist thriller that combines intricate plotting with emotional depth and unforgettable characters.',
    trailerUrl: 'https://www.youtube.com/watch?v=_InQhuuI6dk',
    language: 'Spanish',
    subtitles: ['English', 'Hindi', 'Tamil', 'Telugu', 'French', 'Portuguese'],
    dubbing: ['English', 'Hindi', 'French'],
    poster: 'https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg?auto=compress&cs=tinysrgb&w=400',
    year: 2017,
    genre: ['Crime', 'Drama', 'Thriller'],
    duration: '70 min episodes',
    whyRecommended: 'You\'re feeling bored and want something mind-blowing — this Spanish series offers complex storytelling and emotional depth that will keep you completely engaged.'
  },
  {
    id: '8',
    title: 'Amélie',
    type: 'movie',
    platforms: ['Prime Video', 'Apple TV'],
    imdbRating: 8.3,
    moodScore: 93,
    summary: 'A whimsical French romantic comedy about a shy waitress who decides to help others find happiness.',
    trailerUrl: 'https://www.youtube.com/watch?v=MhodoG26EVs',
    language: 'French',
    subtitles: ['English', 'Spanish', 'German', 'Italian'],
    dubbing: ['English', 'Spanish'],
    poster: 'https://images.pexels.com/photos/3945313/pexels-photo-3945313.jpeg?auto=compress&cs=tinysrgb&w=400',
    year: 2001,
    genre: ['Romance', 'Comedy', 'Drama'],
    duration: '122 min',
    whyRecommended: 'You want to feel uplifted and relaxed — this charming French film offers a whimsical escape into a world of kindness and magical realism.'
  }
];

export const trendingContent: MovieRecommendation[] = [
  mockRecommendations[0], // Kantara
  mockRecommendations[1], // RRR
  mockRecommendations[4], // ZNMD
  mockRecommendations[5]  // Minnal Murali
];